# Generated by Django 5.1.1 on 2025-03-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_delete_pageview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='preferences_completed',
            field=models.BooleanField(default=False),
        ),
    ]
