# Generated by Django 5.1.1 on 2025-03-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliostock',
            name='amount_invested',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='portfoliostock',
            name='price_bought_at',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
