# Generated by Django 5.1.1 on 2025-03-20 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_portfoliostock_amount_invested_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliostock',
            name='price',
        ),
    ]
