# Generated by Django 5.1.1 on 2025-03-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_portfoliostock_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliostock',
            name='company_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
