# Generated by Django 5.1.1 on 2025-03-30 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_portfoliostock_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='investment_type',
        ),
    ]
