# Generated by Django 5.1.1 on 2025-04-01 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_userpreferences_investment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESGCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgperm_id', models.BigIntegerField(unique=True)),
                ('year', models.PositiveIntegerField()),
                ('ticker', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker'], name='api_esgcomp_ticker_ed4322_idx'), models.Index(fields=['orgperm_id'], name='api_esgcomp_orgperm_ddfb87_idx')],
            },
        ),
        migrations.CreateModel(
            name='ESGMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldid', models.PositiveIntegerField()),
                ('hierarchy', models.CharField(max_length=50)),
                ('pillar', models.CharField(max_length=50)),
                ('fieldname', models.CharField(max_length=100)),
                ('valuedate', models.DateField()),
                ('value', models.CharField(max_length=5)),
                ('valuescore', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='api.esgcompany')),
            ],
            options={
                'indexes': [models.Index(fields=['fieldname'], name='api_esgmetr_fieldna_93e2b2_idx'), models.Index(fields=['pillar'], name='api_esgmetr_pillar_52bbe3_idx'), models.Index(fields=['valuescore'], name='api_esgmetr_valuesc_5bf8e1_idx')],
            },
        ),
    ]
