# Generated by Django 5.1.1 on 2025-04-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_esgcompany_esgmetric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esgcompany',
            name='year',
        ),
        migrations.AddField(
            model_name='esgmetric',
            name='year',
            field=models.PositiveIntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='esgmetric',
            index=models.Index(fields=['year'], name='api_esgmetr_year_81191b_idx'),
        ),
    ]
