# Generated by Django 5.1.1 on 2025-04-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_esgcompany_year_esgmetric_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esgcompany',
            name='isin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='esgcompany',
            name='siccode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
