# Generated by Django 5.1.1 on 2025-04-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_esgcompany_isin_esgcompany_siccode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esgcompany',
            name='isin',
            field=models.CharField(blank=True, default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='esgcompany',
            name='siccode',
            field=models.CharField(blank=True, default=1, max_length=10),
            preserve_default=False,
        ),
    ]
