# Generated by Django 5.1.1 on 2025-04-19 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_esgmetric_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esgmetric',
            name='valuedate',
        ),
    ]
