# Generated by Django 5.1.1 on 2025-04-19 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_esgmetric_valuedate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='esgmetric',
            unique_together={('company', 'year', 'fieldid')},
        ),
    ]
